# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Sun Apr 12 21:20:13 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.list_songs = QtGui.QListWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_songs.sizePolicy().hasHeightForWidth())
        self.list_songs.setSizePolicy(sizePolicy)
        self.list_songs.setObjectName("list_songs")
        self.gridLayout.addWidget(self.list_songs, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_new_song = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_new_song.setObjectName("btn_new_song")
        self.horizontalLayout.addWidget(self.btn_new_song)
        self.btn_delete_song = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_delete_song.setObjectName("btn_delete_song")
        self.horizontalLayout.addWidget(self.btn_delete_song)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 2, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_title = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_title.setObjectName("le_title")
        self.gridLayout_2.addWidget(self.le_title, 0, 1, 1, 1)
        self.le_tauthor = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_tauthor.setObjectName("le_tauthor")
        self.gridLayout_2.addWidget(self.le_tauthor, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.le_mauthor = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_mauthor.setObjectName("le_mauthor")
        self.gridLayout_2.addWidget(self.le_mauthor, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.le_year = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_year.setObjectName("le_year")
        self.gridLayout_2.addWidget(self.le_year, 3, 1, 1, 1)
        self.le_tone = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_tone.setObjectName("le_tone")
        self.gridLayout_2.addWidget(self.le_tone, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.te_body = QtGui.QTextEdit(self.gridLayoutWidget)
        self.te_body.setAcceptRichText(False)
        self.te_body.setObjectName("te_body")
        self.verticalLayout.addWidget(self.te_body)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_savesong = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_savesong.setObjectName("btn_savesong")
        self.horizontalLayout_2.addWidget(self.btn_savesong)
        self.btn_create_latex_song = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_create_latex_song.setObjectName("btn_create_latex_song")
        self.horizontalLayout_2.addWidget(self.btn_create_latex_song)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionApri = QtGui.QAction(MainWindow)
        self.actionApri.setObjectName("actionApri")
        self.actionEsci = QtGui.QAction(MainWindow)
        self.actionEsci.setObjectName("actionEsci")
        self.actionSalva = QtGui.QAction(MainWindow)
        self.actionSalva.setObjectName("actionSalva")
        self.actionEsci_2 = QtGui.QAction(MainWindow)
        self.actionEsci_2.setObjectName("actionEsci_2")
        self.actionSalva_canzone = QtGui.QAction(MainWindow)
        self.actionSalva_canzone.setObjectName("actionSalva_canzone")
        self.actionImporta_canzone = QtGui.QAction(MainWindow)
        self.actionImporta_canzone.setObjectName("actionImporta_canzone")
        self.menuFile.addAction(self.actionApri)
        self.menuFile.addAction(self.actionSalva)
        self.menuFile.addAction(self.actionSalva_canzone)
        self.menuFile.addAction(self.actionImporta_canzone)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionEsci_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionEsci_2, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SongBook Editor 0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new_song.setText(QtGui.QApplication.translate("MainWindow", "New Song", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_delete_song.setText(QtGui.QApplication.translate("MainWindow", "Delete Song", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Titolo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Autore Testo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Autore Musica", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Anno", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Tonalità", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_savesong.setText(QtGui.QApplication.translate("MainWindow", "Salva", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_create_latex_song.setText(QtGui.QApplication.translate("MainWindow", "Esporta in LaTeX", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionApri.setText(QtGui.QApplication.translate("MainWindow", "Apri", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEsci.setText(QtGui.QApplication.translate("MainWindow", "Esci", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalva.setText(QtGui.QApplication.translate("MainWindow", "Salva", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEsci_2.setText(QtGui.QApplication.translate("MainWindow", "Esci", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalva_canzone.setText(QtGui.QApplication.translate("MainWindow", "Salva canzone", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImporta_canzone.setText(QtGui.QApplication.translate("MainWindow", "Importa canzone", None, QtGui.QApplication.UnicodeUTF8))

